#!/usr/bin/env bash

set -e

if [ ! -z "$1" ]
  then
    cd $1
fi


if [ ! -z "$2" ]
then
  sudo borg create --compression zstd,8 -c 1200 -p --stats /srv/borg/misc::$(hostname)_${PWD##*/}-$(date +"%Y-%m-%d_%H-%M-%S")-$2 ./
else
  sudo borg create --compression zstd,8 -c 1200 -p --stats /srv/borg/misc::$(hostname)_${PWD##*/}-$(date +"%Y-%m-%d_%H-%M-%S") ./  
fi

if [ ! -z "$1" ]
  then
    cd -
fi

