#!/usr/bin/env bash

# sudo borg create -p --stats --compression auto,zstd,9 /srv/borg/misc::${PWD##*/}-{now:%Y-%m-%dT%H:%M:%S} .
sudo borg create --compression zstd,12 -c 1200 -p --stats /srv/borg/misc::$(hostname)_${PWD##*/}-$(date +"%Y-%m-%d_%H-%M-%S") ./

